name: 'verify-env-against-example'
description: 'A GitHub Action to verify that the environment variables in the current environment match the example environment file'
author: 'jxshco'
inputs:
  env-file:
    description: 'The path to the environment file to compare'
    required: true
    default: '.env'
  example-env-file:
    description: 'The path to the example environment file to compare against'
    required: true
    default: '.env.example'
runs:
  using: 'node16'
  main: 'dist/index.js'
